# Intro to Numpy

In [ ]:
# Numpy lot faster - because optimization code its written in c, Python List is much slower than numpy
# ML - computer understand only numbers 0 or 1's. 
# Numpy - Numerical Python
# Vectorization via broadcasting(avioiding loops)
# Numpy is backbone for other Python Scitific projects

In [2]:
import numpy as np

In [3]:
# Same array as slide in video
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

### 

In [4]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

## DataTypes & Attributes

# Numpy's main datatype is ndarray

In [5]:
a1 = np.array([1,2,3])

In [6]:
a1 # row =1, 3 column (shape(1,3))

array([1, 2, 3])

In [8]:
a2 = np.array([[1,2.0,3.3],
               [4,5.5,6.0]])

In [9]:
a2 # row =2, 3 column (shape(2,3))

array([[1. , 2. , 3.3],
       [4. , 5.5, 6. ]])

In [10]:
type(a2)

numpy.ndarray

In [11]:
type(a1)

numpy.ndarray

In [13]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [14]:
a3 # row =3, 3 column , n = 2 azis - n-refers dimensions  (shape(2,3,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.shape

(3,)

In [16]:
a2.shape

(2, 3)

In [17]:
a3.shape

(2, 3, 3)

In [18]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [19]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [20]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [21]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# create a data frame from numpy array
import pandas as pd
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.5  6.0

In [25]:
df1 = pd.DataFrame(a1)
df1

0
0  1
1  2
2  3

## 2.creating numpy array

In [30]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [31]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
ones.dtype

dtype('float64')

In [34]:
type(ones)

numpy.ndarray

In [35]:
zeros = np.zeros((2,3))

In [36]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
range_array = np.arange(0,10, 2)
range_array

array([0, 2, 4, 6, 8])

In [39]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[3, 7, 3, 6, 2],
       [7, 5, 2, 3, 3],
       [6, 3, 8, 9, 0]])

In [40]:
random_array.size

15

In [41]:
random_array.shape

(3, 5)

In [43]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.29805553, 0.88337292, 0.02519156],
       [0.6022093 , 0.09732207, 0.31453847],
       [0.53112868, 0.33590558, 0.13281709],
       [0.40675296, 0.1856365 , 0.29843473],
       [0.39633647, 0.99374609, 0.79496782]])

In [44]:
random_array2.shape # (Rows, COlumns)

(5, 3)

In [46]:
random_array_3 = np.random.rand(5,3) # d0, d1, d2, ... dimensions
random_array_3

array([[0.94771511, 0.51660224, 0.13690258],
       [0.14811024, 0.90904308, 0.85637625],
       [0.19955561, 0.05472256, 0.39490127],
       [0.39877169, 0.50412522, 0.94126379],
       [0.64299418, 0.04851587, 0.71970687]])

In [47]:
# Pseudo-random numbers
# np.random.seed()
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[2, 6, 4],
       [1, 0, 1],
       [0, 8, 3],
       [7, 8, 3],
       [1, 7, 5]])

In [48]:
random_array_4.shape

(5, 3)

In [52]:
# when you share - with others - to get same numbers at everytime we run ?
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4
# every time you run - output will be same

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [53]:
random_array_4.shape

(5, 3)

In [54]:
np.random.seed(seed=99)
random_array_5 = np.random.randint(10, size=(5,3))
random_array_5

array([[1, 3, 9],
       [8, 9, 8],
       [2, 4, 5],
       [4, 1, 7],
       [3, 7, 1]])

In [56]:
np.random.seed(7) # if you set 
random_array_6 = np.random.random((5,3))
random_array_6

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])