##  3.viewing arrays and matrics

In [1]:
import numpy as np


In [2]:
np.random.seed(seed = 999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 5, 1],
       [8, 1, 9],
       [3, 0, 5],
       [8, 8, 0],
       [5, 2, 5]])

In [3]:
np.unique(random_array_4)

array([0, 1, 2, 3, 5, 8, 9])

In [4]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
                [[7, 8, 9],
                [10, 11, 12]],
                [[13, 14, 15],
                [16, 17, 18]]])

In [5]:
a1 = np.array([1,2,3])

In [7]:
 a1[0]

1

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 1 Dimension is vector
a1

array([1, 2, 3])

In [12]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [13]:
a2.shape

(2, 3)

In [14]:
a2[0]

array([1, 2, 3])

In [16]:
var = "itv" * 2 * 3
print(var)

itvitvitvitvitvitv


In [17]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [18]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [19]:
a4 = np.random.randint(10, size =(2,3,4,5))
# 5 - outside to inside this 5 columns
# 4 - rows
# 3 - 3 array blocks for each 4 rows with 5 colummns
# 2 - 2 outside 

In [20]:
a4

array([[[[7, 4, 6, 2, 7],
         [6, 1, 5, 3, 6],
         [4, 0, 9, 4, 4],
         [8, 7, 2, 7, 4]],

        [[4, 5, 1, 6, 8],
         [9, 1, 1, 1, 6],
         [3, 3, 8, 9, 0],
         [1, 4, 0, 6, 4]],

        [[7, 3, 4, 9, 7],
         [4, 6, 4, 7, 3],
         [0, 4, 4, 6, 8],
         [6, 0, 4, 6, 7]]],


       [[[0, 1, 2, 5, 7],
         [9, 2, 1, 2, 3],
         [3, 2, 3, 3, 4],
         [1, 6, 5, 9, 1]],

        [[2, 2, 3, 8, 0],
         [0, 9, 5, 0, 7],
         [0, 5, 2, 8, 4],
         [6, 8, 9, 4, 7]],

        [[9, 5, 2, 5, 8],
         [3, 3, 9, 9, 9],
         [6, 8, 9, 4, 9],
         [0, 5, 7, 8, 4]]]])

In [21]:
a4.shape

(2, 3, 4, 5)

In [22]:
a1.shape

(3,)

In [23]:
a2.shape

(2, 3)

In [24]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a1

array([1, 2, 3])

In [26]:
a1.ndim

1

In [27]:
a2.ndim

2

In [28]:
a3.ndim

3

In [29]:
a4.ndim

4

In [30]:
# a4 get
a4[:,:,:,:4]

array([[[[7, 4, 6, 2],
         [6, 1, 5, 3],
         [4, 0, 9, 4],
         [8, 7, 2, 7]],

        [[4, 5, 1, 6],
         [9, 1, 1, 1],
         [3, 3, 8, 9],
         [1, 4, 0, 6]],

        [[7, 3, 4, 9],
         [4, 6, 4, 7],
         [0, 4, 4, 6],
         [6, 0, 4, 6]]],


       [[[0, 1, 2, 5],
         [9, 2, 1, 2],
         [3, 2, 3, 3],
         [1, 6, 5, 9]],

        [[2, 2, 3, 8],
         [0, 9, 5, 0],
         [0, 5, 2, 8],
         [6, 8, 9, 4]],

        [[9, 5, 2, 5],
         [3, 3, 9, 9],
         [6, 8, 9, 4],
         [0, 5, 7, 8]]]])

In [31]:
a4[:,:,:,:2]

array([[[[7, 4],
         [6, 1],
         [4, 0],
         [8, 7]],

        [[4, 5],
         [9, 1],
         [3, 3],
         [1, 4]],

        [[7, 3],
         [4, 6],
         [0, 4],
         [6, 0]]],


       [[[0, 1],
         [9, 2],
         [3, 2],
         [1, 6]],

        [[2, 2],
         [0, 9],
         [0, 5],
         [6, 8]],

        [[9, 5],
         [3, 3],
         [6, 8],
         [0, 5]]]])

In [32]:
a4[:2,:,:,:]

array([[[[7, 4, 6, 2, 7],
         [6, 1, 5, 3, 6],
         [4, 0, 9, 4, 4],
         [8, 7, 2, 7, 4]],

        [[4, 5, 1, 6, 8],
         [9, 1, 1, 1, 6],
         [3, 3, 8, 9, 0],
         [1, 4, 0, 6, 4]],

        [[7, 3, 4, 9, 7],
         [4, 6, 4, 7, 3],
         [0, 4, 4, 6, 8],
         [6, 0, 4, 6, 7]]],


       [[[0, 1, 2, 5, 7],
         [9, 2, 1, 2, 3],
         [3, 2, 3, 3, 4],
         [1, 6, 5, 9, 1]],

        [[2, 2, 3, 8, 0],
         [0, 9, 5, 0, 7],
         [0, 5, 2, 8, 4],
         [6, 8, 9, 4, 7]],

        [[9, 5, 2, 5, 8],
         [3, 3, 9, 9, 9],
         [6, 8, 9, 4, 9],
         [0, 5, 7, 8, 4]]]])

In [33]:
a4[:1,:,:,:]

array([[[[7, 4, 6, 2, 7],
         [6, 1, 5, 3, 6],
         [4, 0, 9, 4, 4],
         [8, 7, 2, 7, 4]],

        [[4, 5, 1, 6, 8],
         [9, 1, 1, 1, 6],
         [3, 3, 8, 9, 0],
         [1, 4, 0, 6, 4]],

        [[7, 3, 4, 9, 7],
         [4, 6, 4, 7, 3],
         [0, 4, 4, 6, 8],
         [6, 0, 4, 6, 7]]]])

In [34]:
a4[:1,:1,:1,:]

array([[[[7, 4, 6, 2, 7]]]])

In [35]:
a4[:1,:2,:1,:]

array([[[[7, 4, 6, 2, 7]],

        [[4, 5, 1, 6, 8]]]])

In [36]:
a4[:1,:3,:1,:]

array([[[[7, 4, 6, 2, 7]],

        [[4, 5, 1, 6, 8]],

        [[7, 3, 4, 9, 7]]]])

# Manipulating Arrays & comparing Arrays

## Arithmetic

In [40]:
a1


array([1, 2, 3])

In [42]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [43]:
a1 + ones

array([2., 3., 4.])

In [44]:
a1 - ones

array([0., 1., 2.])

In [45]:
a1 * ones

array([1., 2., 3.])

In [46]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a1 * a2
# [1., 2., 3.] * [1, 2, 3]
# [1., 2., 3.] *  [4, 5, 6]

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [48]:
a2 * a3

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [49]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18]],

       [[ 7, 16, 27],
        [10, 22, 36]],

       [[13, 28, 45],
        [16, 34, 54]]])

In [50]:
# How to reshape a2 to a3 ?
a1 / ones

array([1., 2., 3.])

In [51]:
# Floor divsion removed the decimals (rounds down)
a2 // a1 

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [52]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [53]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [54]:
np.square(a2) # you can use

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [55]:
np.add(a1, ones)

array([2., 3., 4.])

In [56]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [57]:
np.mod(a1, 2)

array([1, 0, 1], dtype=int32)

In [58]:
np.divide(a1, 2)

array([0.5, 1. , 1.5])

In [59]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

# aggregation 
Aggregation = performing the same operation on number of things

In [61]:
listy_list = [1,2,3]
type(listy_list)

list

In [62]:
sum(listy_list)

6

In [63]:
a1

array([1, 2, 3])

In [64]:
sum(a1)

6

In [65]:
np.sum(a1)

6

In [66]:
#use pythons methods on Pythion dataType , use numpy methods on Numpy

In [68]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [69]:
massive_array[:10]

array([0.61853275, 0.65194493, 0.92514612, 0.42859065, 0.11154318,
       0.1621305 , 0.82104082, 0.56651826, 0.92231069, 0.75206744])

In [70]:
%timeit sum(massive_array) # Pythons's Sum()
%timeit np.sum(massive_array) # Numpy's sum()

10.2 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
43.1 µs ± 3.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
10200 micro seconds is equal 10.2 ms seconds

In [71]:
10200 / 43 # this times faster than Pythons sum

237.2093023255814

In [72]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.mean(a2)

3.5

In [74]:
np.max(a2)

6

In [75]:
np.min(a2)

1

In [76]:
# standard deviation = a measure of how spread out a group of numbers
np.std(a2)

1.707825127659933

In [78]:
# Variance = measure of the average degree to which each number is difference
# Higher variance = wider range of number
# Lower variance = lower range of numbers
np.var(a2)

2.9166666666666665